### ISSUE TITLE
`EnsureValidNullability` doesn't work with records

### ISSUE THREAD

**Issue by maxkoshevoi** [RicoSuter/Namotion.Reflection#103]
I'm trying to use `EnsureValidNullability` in my project, but it always crashes on any record with:
```cs
System.InvalidOperationException: 'Method may only be called on a Type for which Type.IsGenericParameter is true.'
```

**Comment by maxkoshevoi** [comment]
@RicoSuter could you please take a look at this?

**Comment by cfbao** [comment]
Preliminary investigation suggests this issue is caused by recursively checking nullability of the compiler generated [`EqualityContract`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/records#equality-members) property on record objects.

https://github.com/RicoSuter/Namotion.Reflection/pull/126 has a tentative fix (no tests...) that ignores all properties with `CompilerGeneratedAttribute`. This makes `EnsureValidNullability` and `ValidateNullability` usable on records. I'm not 100% sure if this is entirely backwards compatible, but it seems to me checking nullability on compiler generated properties is unlikely what users want/need.

**Comment by JesseNewman19** [comment]
For funsies I pulled down the code in that PR and tested it against some of my records and I still ran into that error.

**Comment by Methuselah96** [comment]
FWIW, the PR fixed it for me.
